unit Uconnecta;

{*******************************************************************************
    Generated By   : JsonToDelphiClass - 0.65 
    Project link   : https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
    Generated On   : 2019-10-15 09:36:44

    Created By     : Petar Georgiev - (http://pgeorgiev.com) 
    Adapted Web By : Marlon Nardi - (http://jsontodelphi.com)
*******************************************************************************}

interface

uses Generics.Collections, Rest.Json;

type

TCCFBACENClass = class
private
  FAlerta: String;
  FDataMaisAntigo: String;
  FDataMaisRecente: String;
  FNomeMaisRecente: String;
  FNomeRegistro: String;
  FPeriodo: String;
  FQuantidade: String;
  FValorTotal: String;
public
  property alerta: String read FAlerta write FAlerta;
  property dataMaisAntigo: String read FDataMaisAntigo write FDataMaisAntigo;
  property dataMaisRecente: String read FDataMaisRecente write FDataMaisRecente;
  property nomeMaisRecente: String read FNomeMaisRecente write FNomeMaisRecente;
  property nomeRegistro: String read FNomeRegistro write FNomeRegistro;
  property periodo: String read FPeriodo write FPeriodo;
  property quantidade: String read FQuantidade write FQuantidade;
  property valorTotal: String read FValorTotal write FValorTotal;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TCCFBACENClass;
end;

TPROTESTOClass = class
private
  FAlerta: String;
  FDataMaisAntigo: String;
  FDataMaisRecente: String;
  FNomeMaisRecente: String;
  FNomeRegistro: String;
  FPeriodo: String;
  FQuantidade: String;
  FValorTotal: String;
public
  property alerta: String read FAlerta write FAlerta;
  property dataMaisAntigo: String read FDataMaisAntigo write FDataMaisAntigo;
  property dataMaisRecente: String read FDataMaisRecente write FDataMaisRecente;
  property nomeMaisRecente: String read FNomeMaisRecente write FNomeMaisRecente;
  property nomeRegistro: String read FNomeRegistro write FNomeRegistro;
  property periodo: String read FPeriodo write FPeriodo;
  property quantidade: String read FQuantidade write FQuantidade;
  property valorTotal: String read FValorTotal write FValorTotal;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TPROTESTOClass;
end;

TPEFINDClass = class
private
  FAlerta: String;
  FDataMaisAntigo: String;
  FDataMaisRecente: String;
  FNomeMaisRecente: String;
  FNomeRegistro: String;
  FPeriodo: String;
  FQuantidade: String;
  FValorTotal: String;
public
  property alerta: String read FAlerta write FAlerta;
  property dataMaisAntigo: String read FDataMaisAntigo write FDataMaisAntigo;
  property dataMaisRecente: String read FDataMaisRecente write FDataMaisRecente;
  property nomeMaisRecente: String read FNomeMaisRecente write FNomeMaisRecente;
  property nomeRegistro: String read FNomeRegistro write FNomeRegistro;
  property periodo: String read FPeriodo write FPeriodo;
  property quantidade: String read FQuantidade write FQuantidade;
  property valorTotal: String read FValorTotal write FValorTotal;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TPEFINDClass;
end;

TPEFINVClass = class
private
  FAlerta: String;
  FDataMaisAntigo: String;
  FDataMaisRecente: String;
  FNomeMaisRecente: String;
  FNomeRegistro: String;
  FPeriodo: String;
  FQuantidade: String;
  FValorTotal: String;
public
  property alerta: String read FAlerta write FAlerta;
  property dataMaisAntigo: String read FDataMaisAntigo write FDataMaisAntigo;
  property dataMaisRecente: String read FDataMaisRecente write FDataMaisRecente;
  property nomeMaisRecente: String read FNomeMaisRecente write FNomeMaisRecente;
  property nomeRegistro: String read FNomeRegistro write FNomeRegistro;
  property periodo: String read FPeriodo write FPeriodo;
  property quantidade: String read FQuantidade write FQuantidade;
  property valorTotal: String read FValorTotal write FValorTotal;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TPEFINVClass;
end;

TPENDINTERNASClass = class
private
  FAlerta: String;
  FDataMaisAntigo: String;
  FDataMaisRecente: String;
  FNomeMaisRecente: String;
  FNomeRegistro: String;
  FPeriodo: String;
  FQuantidade: String;
  FValorTotal: String;
public
  property alerta: String read FAlerta write FAlerta;
  property dataMaisAntigo: String read FDataMaisAntigo write FDataMaisAntigo;
  property dataMaisRecente: String read FDataMaisRecente write FDataMaisRecente;
  property nomeMaisRecente: String read FNomeMaisRecente write FNomeMaisRecente;
  property nomeRegistro: String read FNomeRegistro write FNomeRegistro;
  property periodo: String read FPeriodo write FPeriodo;
  property quantidade: String read FQuantidade write FQuantidade;
  property valorTotal: String read FValorTotal write FValorTotal;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TPENDINTERNASClass;
end;

TRootClass = class
private
  FCCFBACEN: TCCFBACENClass;
  FPEFIND: TPEFINDClass;
  FPEFINV: TPEFINVClass;
  FPENDINTERNAS: TPENDINTERNASClass;
  FPROTESTO: TPROTESTOClass;
public
  property CCFBACEN: TCCFBACENClass read FCCFBACEN write FCCFBACEN;
  property PEFIND: TPEFINDClass read FPEFIND write FPEFIND;
  property PEFINV: TPEFINVClass read FPEFINV write FPEFINV;
  property PENDINTERNAS: TPENDINTERNASClass read FPENDINTERNAS write FPENDINTERNAS;
  property PROTESTO: TPROTESTOClass read FPROTESTO write FPROTESTO;
  constructor Create;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TRootClass;
end;

implementation

{TCCFBACENClass}


function TCCFBACENClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TCCFBACENClass.FromJsonString(AJsonString: string): TCCFBACENClass;
begin
  result := TJson.JsonToObject<TCCFBACENClass>(AJsonString)
end;

{TPROTESTOClass}


function TPROTESTOClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TPROTESTOClass.FromJsonString(AJsonString: string): TPROTESTOClass;
begin
  result := TJson.JsonToObject<TPROTESTOClass>(AJsonString)
end;

{TPEFINDClass}


function TPEFINDClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TPEFINDClass.FromJsonString(AJsonString: string): TPEFINDClass;
begin
  result := TJson.JsonToObject<TPEFINDClass>(AJsonString)
end;

{TPEFINVClass}


function TPEFINVClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TPEFINVClass.FromJsonString(AJsonString: string): TPEFINVClass;
begin
  result := TJson.JsonToObject<TPEFINVClass>(AJsonString)
end;

{TPENDINTERNASClass}


function TPENDINTERNASClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TPENDINTERNASClass.FromJsonString(AJsonString: string): TPENDINTERNASClass;
begin
  result := TJson.JsonToObject<TPENDINTERNASClass>(AJsonString)
end;

{TRootClass}

constructor TRootClass.Create;
begin
  inherited;
  FPENDINTERNAS := TPENDINTERNASClass.Create();
  FPEFINV := TPEFINVClass.Create();
  FPEFIND := TPEFINDClass.Create();
  FPROTESTO := TPROTESTOClass.Create();
  FCCFBACEN := TCCFBACENClass.Create();
end;

destructor TRootClass.Destroy;
begin
  FPENDINTERNAS.Free;
  FPEFINV.Free;
  FPEFIND.Free;
  FPROTESTO.Free;
  FCCFBACEN.Free;
  inherited;
end;

function TRootClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TRootClass.FromJsonString(AJsonString: string): TRootClass;
begin
  result := TJson.JsonToObject<TRootClass>(AJsonString)
end;

end.
