unit URecupera_Saldos;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, DB, IBCustomDataSet, IBQuery, StdCtrls, Buttons, ExtCtrls, Mask,
  rxToolEdit, FireDAC.Stan.Intf, FireDAC.Stan.Option, FireDAC.Stan.Param,
  FireDAC.Stan.Error, FireDAC.DatS, FireDAC.Phys.Intf, FireDAC.DApt.Intf,
  FireDAC.Stan.Async, FireDAC.DApt, FireDAC.Comp.DataSet, FireDAC.Comp.Client;

type
  TFrmRecupera_Saldos = class(TForm)
    Label1: TLabel;
    Dtmen: TDateEdit;
    Dtmai: TDateEdit;
    Bevel1: TBevel;
    btnExecuta: TBitBtn;
    btnRetorna: TBitBtn;
    QArq: TFDQuery;
    procedure FormCreate(Sender: TObject);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
    procedure DtmenKeyDown(Sender: TObject; var Key: Word; Shift: TShiftState);
    procedure DtmenEnter(Sender: TObject);
    procedure btnRetornaClick(Sender: TObject);
    procedure btnExecutaClick(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  FrmRecupera_Saldos: TFrmRecupera_Saldos;

implementation

uses
  UData, UPrincipal;

{$R *.dfm}

procedure TFrmRecupera_Saldos.btnExecutaClick(Sender: TObject);
begin
  try
    btnExecuta.Enabled := False;
    btnRetorna.Enabled := False;

    QArq.Sql.Clear;
    QArq.Sql.Add('DELETE FROM RAZAO');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TIPO_TRANSACAO <> :TIPO_TRANSACAO)');
    QArq.Sql.Add('AND (DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'M';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Transação Entre Bancos (DB Destino - CR Origem)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_ENT_SAI, TRANSACOES.DT_MOVIMENTO, BCO_DEBITO.COD_CONTABIL, BCO_CREDITO.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC');
    QArq.Sql.Add('FROM TRANSACOES');
    QArq.Sql.Add('INNER JOIN BANCOS BCO_DEBITO');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID_TRANSF = BCO_DEBITO.BANCO_ID)');
    QArq.Sql.Add('INNER JOIN BANCOS BCO_CREDITO');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BCO_CREDITO.BANCO_ID)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.DEPTO = :DEPTO)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('CONDUTA').AsString        := '02';
    QArq.ParamByName('DEPTO').AsString          := '04';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Crédito a Vista (DB Cx/Bco - CR Cta.)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_ENT_SAI, TRANSACOES.DT_MOVIMENTO, BANCOS.COD_CONTABIL, TABELAS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    QArq.Sql.Add('FROM TRANSACOES');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('INNER JOIN TABELAS');
    QArq.Sql.Add('ON (TRANSACOES.CONTA_ID = TABELAS.TABELA_ID AND TABELAS.TIPO_TABELA = :TIPO_TABELA)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.DEPTO = :DEPTO)');
    QArq.Sql.Add('AND (TRANSACOES.COND_PAGTO = :COND_PAGTO)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('TIPO_TABELA').AsString    := '4';
    QArq.ParamByName('CONDUTA').AsString        := '01';
    QArq.ParamByName('DEPTO').AsString          := '03';
    QArq.ParamByName('COND_PAGTO').AsString     := 'A VISTA';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Crédito a Prazo (DB Cliente - CR Cta.)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_ENT_SAI, TRANSACOES.DT_MOVIMENTO, CLIENTES.COD_CONTABIL, TABELAS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC');
    QArq.Sql.Add('FROM TRANSACOES');
    QArq.Sql.Add('INNER JOIN CLIENTES');
    QArq.Sql.Add('ON (TRANSACOES.CLIENTE_ID = CLIENTES.CLIENTE_ID)');
    QArq.Sql.Add('INNER JOIN TABELAS');
    QArq.Sql.Add('ON (TRANSACOES.CONTA_ID = TABELAS.TABELA_ID AND TABELAS.TIPO_TABELA = :TIPO_TABELA)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.DEPTO = :DEPTO)');
    QArq.Sql.Add('AND (TRANSACOES.COND_PAGTO = :COND_PAGTO)');
    QArq.Sql.Add('AND (TRANSACOES.BALANCO <> :BALANCO)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('TIPO_TABELA').AsString    := '4';
    QArq.ParamByName('CONDUTA').AsString        := '01';
    QArq.ParamByName('DEPTO').AsString          := '03';
    QArq.ParamByName('COND_PAGTO').AsString     := 'A PRAZO';
    QArq.ParamByName('BALANCO').AsString        := 'AGRUPADO';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Recebimento c/ Desconto (DB Cx/Bco - CR Cliente) - (DB Cta. - CR Cliente)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, BANCOS.COD_CONTABIL, CLIENTES.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    QArq.Sql.Add('FROM TRANSACOES');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('INNER JOIN CLIENTES');
    QArq.Sql.Add('ON (TRANSACOES.CLIENTE_ID = CLIENTES.CLIENTE_ID)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.SERIE = :SERIE)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('CONDUTA').AsString        := '07';
    QArq.ParamByName('SERIE').AsString          := 'D';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, TABELAS.COD_CONTABIL, CLIENTES.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.COMPLEMENTO, (TRANSACOES.VALOR_PARCELA - TRANSACOES.VALOR), TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC');
    QArq.Sql.Add('FROM TRANSACOES');
    QArq.Sql.Add('INNER JOIN TABELAS');
    QArq.Sql.Add('ON (TRANSACOES.CONTA_ID = TABELAS.TABELA_ID AND TABELAS.TIPO_TABELA = :TIPO_TABELA)');
    QArq.Sql.Add('INNER JOIN CLIENTES');
    QArq.Sql.Add('ON (TRANSACOES.CLIENTE_ID = CLIENTES.CLIENTE_ID)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.SERIE = :SERIE)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('TIPO_TABELA').AsString    := '4';
    QArq.ParamByName('CONDUTA').AsString        := '07';
    QArq.ParamByName('SERIE').AsString          := 'D';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Recebimento c/ Juros (DB Cx/Bco - CR Cliente) - (DB Cx/Bco - CR Cta.)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, BANCOS.COD_CONTABIL, CLIENTES.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR_PARCELA, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    QArq.Sql.Add('FROM TRANSACOES');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('INNER JOIN CLIENTES');
    QArq.Sql.Add('ON (TRANSACOES.CLIENTE_ID = CLIENTES.CLIENTE_ID)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.SERIE = :SERIE)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('CONDUTA').AsString        := '07';
    QArq.ParamByName('SERIE').AsString          := 'J';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, BANCOS.COD_CONTABIL, TABELAS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.COMPLEMENTO, (TRANSACOES.VALOR - TRANSACOES.VALOR_PARCELA), TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    QArq.Sql.Add('FROM TRANSACOES');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('INNER JOIN TABELAS');
    QArq.Sql.Add('ON (TRANSACOES.CONTA_ID = TABELAS.TABELA_ID AND TABELAS.TIPO_TABELA = :TIPO_TABELA)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.SERIE = :SERIE)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('TIPO_TABELA').AsString    := '4';
    QArq.ParamByName('CONDUTA').AsString        := '07';
    QArq.ParamByName('SERIE').AsString          := 'J';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Recebimento Integral (DB Cx/Bco - CR Cliente)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, BANCOS.COD_CONTABIL, CLIENTES.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    QArq.Sql.Add('FROM TRANSACOES');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('INNER JOIN CLIENTES');
    QArq.Sql.Add('ON (TRANSACOES.CLIENTE_ID = CLIENTES.CLIENTE_ID)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.SERIE = :SERIE)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('CONDUTA').AsString        := '07';
    QArq.ParamByName('SERIE').AsString          := 'N';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Recebimento Parcial (DB Cx/Bco - CR Cliente)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, BANCOS.COD_CONTABIL, CLIENTES.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    QArq.Sql.Add('FROM TRANSACOES');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('INNER JOIN CLIENTES');
    QArq.Sql.Add('ON (TRANSACOES.CLIENTE_ID = CLIENTES.CLIENTE_ID)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.SERIE = :SERIE)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('CONDUTA').AsString        := '07';
    QArq.ParamByName('SERIE').AsString          := 'P';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Débito a Vista (CR Cx/Bco - DB Cta.)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_ENT_SAI, TRANSACOES.DT_MOVIMENTO, TABELAS.COD_CONTABIL, BANCOS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    QArq.Sql.Add('FROM TRANSACOES');
    QArq.Sql.Add('INNER JOIN TABELAS');
    QArq.Sql.Add('ON (TRANSACOES.CONTA_ID = TABELAS.TABELA_ID AND TABELAS.TIPO_TABELA = :TIPO_TABELA)');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.DEPTO = :DEPTO)');
    QArq.Sql.Add('AND (TRANSACOES.COND_PAGTO = :COND_PAGTO)');
    QArq.Sql.Add('AND (TRANSACOES.DT_ENT_SAI BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('TIPO_TABELA').AsString    := '4';
    QArq.ParamByName('CONDUTA').AsString        := '02';
    QArq.ParamByName('DEPTO').AsString          := '02';
    QArq.ParamByName('COND_PAGTO').AsString     := 'A VISTA';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Débito a Prazo (DB Cta. - CR Fornecedor)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_ENT_SAI, TRANSACOES.DT_MOVIMENTO, TABELAS.COD_CONTABIL, FORNECEDORES.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC');
    QArq.Sql.Add('FROM TRANSACOES');
    QArq.Sql.Add('INNER JOIN TABELAS');
    QArq.Sql.Add('ON (TRANSACOES.CONTA_ID = TABELAS.TABELA_ID AND TABELAS.TIPO_TABELA = :TIPO_TABELA)');
    QArq.Sql.Add('INNER JOIN FORNECEDORES');
    QArq.Sql.Add('ON (TRANSACOES.FORNECEDOR_ID = FORNECEDORES.FORNECEDOR_ID)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.DEPTO = :DEPTO)');
    QArq.Sql.Add('AND (TRANSACOES.COND_PAGTO = :COND_PAGTO)');
    QArq.Sql.Add('AND (TRANSACOES.BALANCO <> :BALANCO)');
    QArq.Sql.Add('AND (TRANSACOES.DT_ENT_SAI BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('TIPO_TABELA').AsString    := '4';
    QArq.ParamByName('CONDUTA').AsString        := '02';
    QArq.ParamByName('DEPTO').AsString          := '02';
    QArq.ParamByName('COND_PAGTO').AsString     := 'A PRAZO';
    QArq.ParamByName('BALANCO').AsString        := 'AGRUPADO';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Pagamento c/ Desconto (DB Fornecedor - CR Cx/Bco.) - (DB Fornecedor - CR Cta.)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, FORNECEDORES.COD_CONTABIL, BANCOS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    QArq.Sql.Add('FROM TRANSACOES');
    QArq.Sql.Add('INNER JOIN FORNECEDORES');
    QArq.Sql.Add('ON (TRANSACOES.FORNECEDOR_ID = FORNECEDORES.FORNECEDOR_ID)');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.SERIE = :SERIE)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('CONDUTA').AsString        := '08';
    QArq.ParamByName('SERIE').AsString          := 'D';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, FORNECEDORES.COD_CONTABIL, TABELAS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.COMPLEMENTO, (TRANSACOES.VALOR_PARCELA - TRANSACOES.VALOR), TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC');
    QArq.Sql.Add('FROM TRANSACOES');
    QArq.Sql.Add('INNER JOIN FORNECEDORES');
    QArq.Sql.Add('ON (TRANSACOES.FORNECEDOR_ID = FORNECEDORES.FORNECEDOR_ID)');
    QArq.Sql.Add('INNER JOIN TABELAS');
    QArq.Sql.Add('ON (TRANSACOES.CONTA_ID = TABELAS.TABELA_ID AND TABELAS.TIPO_TABELA = :TIPO_TABELA)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.SERIE = :SERIE)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('TIPO_TABELA').AsString    := '4';
    QArq.ParamByName('CONDUTA').AsString        := '08';
    QArq.ParamByName('SERIE').AsString          := 'D';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Pagamento c/ Juros (DB Fornecedor - CR Cx/Bco.) - (DB Cta. - CR Cx/Bco.)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, FORNECEDORES.COD_CONTABIL, BANCOS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR_PARCELA, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    QArq.Sql.Add('FROM TRANSACOES');
    QArq.Sql.Add('INNER JOIN FORNECEDORES');
    QArq.Sql.Add('ON (TRANSACOES.FORNECEDOR_ID = FORNECEDORES.FORNECEDOR_ID)');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.SERIE = :SERIE)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('CONDUTA').AsString        := '08';
    QArq.ParamByName('SERIE').AsString          := 'J';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, TABELAS.COD_CONTABIL, BANCOS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.COMPLEMENTO, (TRANSACOES.VALOR - TRANSACOES.VALOR_PARCELA), TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    QArq.Sql.Add('FROM TRANSACOES');
    QArq.Sql.Add('INNER JOIN TABELAS');
    QArq.Sql.Add('ON (TRANSACOES.CONTA_ID = TABELAS.TABELA_ID AND TABELAS.TIPO_TABELA = :TIPO_TABELA)');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.SERIE = :SERIE)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('TIPO_TABELA').AsString    := '4';
    QArq.ParamByName('CONDUTA').AsString        := '08';
    QArq.ParamByName('SERIE').AsString          := 'J';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Pagamento Integral (DB Fornecedor - CR Cx/Bco.)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, FORNECEDORES.COD_CONTABIL, BANCOS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    QArq.Sql.Add('FROM TRANSACOES');
    QArq.Sql.Add('INNER JOIN FORNECEDORES');
    QArq.Sql.Add('ON (TRANSACOES.FORNECEDOR_ID = FORNECEDORES.FORNECEDOR_ID)');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.SERIE = :SERIE)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('CONDUTA').AsString        := '08';
    QArq.ParamByName('SERIE').AsString          := 'N';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Pagamento Parcial (DB Fornecedor - CR Cx/Bco.)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, FORNECEDORES.COD_CONTABIL, BANCOS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    QArq.Sql.Add('FROM TRANSACOES');
    QArq.Sql.Add('INNER JOIN FORNECEDORES');
    QArq.Sql.Add('ON (TRANSACOES.FORNECEDOR_ID = FORNECEDORES.FORNECEDOR_ID)');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.SERIE = :SERIE)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('CONDUTA').AsString        := '08';
    QArq.ParamByName('SERIE').AsString          := 'P';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Compra a Vista (DB Cta. - CR Cx/Bco.)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_ENT_SAI, TRANSACOES.DT_MOVIMENTO, TABELAS.COD_CONTABIL, BANCOS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    //SUM(TRANSITENS.VR_TOTAL + TRANSITENS.VALOR_ICMS_ST + TRANSITENS.VR_FRETE + TRANSITENS.VR_ACRESCIMO + TRANSITENS.VR_IPI - TRANSITENS.DESC_RODAPE)
    QArq.Sql.Add('FROM TRANSACOES');
    //QArq.Sql.Add('INNER JOIN TRANSACOES');
    //QArq.Sql.Add('ON (TRANSITENS.TRANSACAO_ID = TRANSACOES.TRANSACAO_ID)');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('INNER JOIN TABELAS');
    QArq.Sql.Add('ON (TRANSACOES.CONTA_ID = TABELAS.TABELA_ID AND TABELAS.TIPO_TABELA = :TIPO_TABELA)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.DEPTO = :DEPTO)');
    QArq.Sql.Add('AND (TRANSACOES.COND_PAGTO = :COND_PAGTO)');
    QArq.Sql.Add('AND (TRANSACOES.DT_ENT_SAI BETWEEN :DT_INICIAL AND :DT_FINAL)');
    //QArq.Sql.Add('GROUP BY TRANSITENS.TRANSACAO_ID, TRANSACOES.DT_ENT_SAI, TRANSACOES.DT_MOVIMENTO, TABELAS.COD_CONTABIL, BANCOS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
    //             'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('TIPO_TABELA').AsString    := '4';
    QArq.ParamByName('CONDUTA').AsString        := '02';
    QArq.ParamByName('DEPTO').AsString          := '07';
    QArq.ParamByName('COND_PAGTO').AsString     := 'A VISTA';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Compra a Prazo (DB Cta. - CR Fornecedor)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_ENT_SAI, TRANSACOES.DT_MOVIMENTO, TABELAS.COD_CONTABIL, FORNECEDORES.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO,TRANSACOES.VALOR , TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC');
    //SUM(TRANSITENS.VR_TOTAL + TRANSITENS.VALOR_ICMS_ST + TRANSITENS.VR_FRETE + TRANSITENS.VR_ACRESCIMO + TRANSITENS.VR_IPI - TRANSITENS.DESC_RODAPE)
    QArq.Sql.Add('FROM TRANSACOES');
    //QArq.Sql.Add('INNER JOIN TRANSACOES');
    //QArq.Sql.Add('ON (TRANSITENS.TRANSACAO_ID = TRANSACOES.TRANSACAO_ID)');
    QArq.Sql.Add('INNER JOIN FORNECEDORES');
    QArq.Sql.Add('ON (TRANSACOES.FORNECEDOR_ID = FORNECEDORES.FORNECEDOR_ID)');
    QArq.Sql.Add('INNER JOIN TABELAS');
    QArq.Sql.Add('ON (TRANSACOES.CONTA_ID = TABELAS.TABELA_ID AND TABELAS.TIPO_TABELA = :TIPO_TABELA)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.DEPTO = :DEPTO)');
    QArq.Sql.Add('AND (TRANSACOES.COND_PAGTO = :COND_PAGTO)');
    QArq.Sql.Add('AND (TRANSACOES.BALANCO <> :BALANCO)');
    QArq.Sql.Add('AND (TRANSACOES.DT_ENT_SAI BETWEEN :DT_INICIAL AND :DT_FINAL)');
  //  QArq.Sql.Add('GROUP BY TRANSITENS.TRANSACAO_ID, TRANSACOES.DT_ENT_SAI, TRANSACOES.DT_MOVIMENTO, TABELAS.COD_CONTABIL, FORNECEDORES.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
  //               'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('TIPO_TABELA').AsString    := '4';
    QArq.ParamByName('CONDUTA').AsString        := '02';
    QArq.ParamByName('DEPTO').AsString          := '07';
    QArq.ParamByName('COND_PAGTO').AsString     := 'A PRAZO';
    QArq.ParamByName('BALANCO').AsString        := 'AGRUPADO';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Devolução de Compra (DB Cta. - CR Cx/Bco.)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_ENT_SAI, TRANSACOES.DT_MOVIMENTO,BANCOS.COD_CONTABIL, TABELAS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO,TRANSACOES.VALOR , TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    //SUM(TRANSITENS.VR_TOTAL + TRANSITENS.VALOR_ICMS_ST + TRANSITENS.VR_FRETE + TRANSITENS.VR_ACRESCIMO + TRANSITENS.VR_IPI - TRANSITENS.DESC_RODAPE)
    QArq.Sql.Add('FROM TRANSACOES');
    //QArq.Sql.Add('INNER JOIN TRANSACOES');
    //QArq.Sql.Add('ON (TRANSITENS.TRANSACAO_ID = TRANSACOES.TRANSACAO_ID)');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('INNER JOIN TABELAS');
    QArq.Sql.Add('ON (TRANSACOES.CONTA_ID = TABELAS.TABELA_ID AND TABELAS.TIPO_TABELA = :TIPO_TABELA)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.DEPTO = :DEPTO)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');
  //  QArq.Sql.Add('GROUP BY TRANSITENS.TRANSACAO_ID, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, BANCOS.COD_CONTABIL, TABELAS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
  //               'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('TIPO_TABELA').AsString    := '4';
    QArq.ParamByName('CONDUTA').AsString        := '01';
    QArq.ParamByName('DEPTO').AsString          := '10';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Venda a Vista (DB Cx/Bco. - CR Cta.)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSITENS.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, BANCOS.COD_CONTABIL, TABELAS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, SUM(TRANSITENS.VR_TOTAL + TRANSITENS.VALOR_ICMS_ST + TRANSITENS.VR_FRETE + TRANSITENS.VR_ACRESCIMO + TRANSITENS.VR_IPI - TRANSITENS.DESC_RODAPE) , TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    //
    QArq.Sql.Add('FROM TRANSITENS');
    QArq.Sql.Add('INNER JOIN TRANSACOES');
    QArq.Sql.Add('ON (TRANSITENS.TRANSACAO_ID = TRANSACOES.TRANSACAO_ID)');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('INNER JOIN TABELAS');
    QArq.Sql.Add('ON (TRANSACOES.CONTA_ID = TABELAS.TABELA_ID AND TABELAS.TIPO_TABELA = :TIPO_TABELA)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.DEPTO = :DEPTO)');
    QArq.Sql.Add('AND (TRANSACOES.MODELO = :MODELO)');
    QArq.Sql.Add('AND ((TRANSACOES.COND_PAGTO IN(:COND_PAGTO,:COND_PAGTO1,:COND_PAGTO2,:COND_PAGTO3)))');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');
    QArq.Sql.Add('GROUP BY TRANSITENS.TRANSACAO_ID, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, TABELAS.COD_CONTABIL, BANCOS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('TIPO_TABELA').AsString    := '4';
    QArq.ParamByName('CONDUTA').AsString        := '01';
    QArq.ParamByName('DEPTO').AsString          := '07';
    QArq.ParamByName('MODELO').AsString         := '2D';
    QArq.ParamByName('COND_PAGTO').AsString     := 'A VISTA';
    QArq.ParamByName('COND_PAGTO1').AsString    := 'CARTAO';
    QArq.ParamByName('COND_PAGTO2').AsString    := 'PIX';
    QArq.ParamByName('COND_PAGTO3').AsString    := 'CHEQUE';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Venda a Prazo (DB Cliente - CR Cta.)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, CLIENTES.COD_CONTABIL, TABELAS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR , TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC');
    //SUM(TRANSITENS.VR_TOTAL + TRANSITENS.VALOR_ICMS_ST + TRANSITENS.VR_FRETE + TRANSITENS.VR_ACRESCIMO + TRANSITENS.VR_IPI - TRANSITENS.DESC_RODAPE)

    QArq.Sql.Add('FROM TRANSACOES');
   // QArq.Sql.Add('INNER JOIN TRANSACOES');
   // QArq.Sql.Add('ON (TRANSITENS.TRANSACAO_ID = TRANSACOES.TRANSACAO_ID)');
    QArq.Sql.Add('INNER JOIN CLIENTES');
    QArq.Sql.Add('ON (TRANSACOES.CLIENTE_ID = CLIENTES.CLIENTE_ID)');
    QArq.Sql.Add('INNER JOIN TABELAS');
    QArq.Sql.Add('ON (TRANSACOES.CONTA_ID = TABELAS.TABELA_ID AND TABELAS.TIPO_TABELA = :TIPO_TABELA)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.DEPTO = :DEPTO)');
    QArq.Sql.Add('AND (TRANSACOES.MODELO = :MODELO)');
    QArq.Sql.Add('AND (TRANSACOES.COND_PAGTO = :COND_PAGTO)');
    QArq.Sql.Add('AND (TRANSACOES.BALANCO <> :BALANCO)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');
 //   QArq.Sql.Add('GROUP BY TRANSITENS.TRANSACAO_ID, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, CLIENTES.COD_CONTABIL, TABELAS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
 //                'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('TIPO_TABELA').AsString    := '4';
    QArq.ParamByName('CONDUTA').AsString        := '01';
    QArq.ParamByName('DEPTO').AsString          := '07';
    QArq.ParamByName('MODELO').AsString         := '2D';
    QArq.ParamByName('COND_PAGTO').AsString     := 'A PRAZO';
    QArq.ParamByName('BALANCO').AsString        := 'AGRUPADO';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Venda a Vista Nfe (DB Cx/Bco. - CR Cta.)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_ENT_SAI, TRANSACOES.DT_MOVIMENTO, BANCOS.COD_CONTABIL, TABELAS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR , TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    //SUM(TRANSITENS.VR_TOTAL + TRANSITENS.VALOR_ICMS_ST + TRANSITENS.VR_FRETE + TRANSITENS.VR_ACRESCIMO + TRANSITENS.VR_IPI - TRANSITENS.DESC_RODAPE)
    QArq.Sql.Add('FROM TRANSACOES');
    //QArq.Sql.Add('INNER JOIN TRANSACOES');
    //QArq.Sql.Add('ON (TRANSITENS.TRANSACAO_ID = TRANSACOES.TRANSACAO_ID)');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('INNER JOIN TABELAS');
    QArq.Sql.Add('ON (TRANSACOES.CONTA_ID = TABELAS.TABELA_ID AND TABELAS.TIPO_TABELA = :TIPO_TABELA)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.DEPTO = :DEPTO)');
    QArq.Sql.Add('AND (TRANSACOES.MODELO <> :MODELO)');
    // POISLER 03/06/2023
    // trocado o "or" por "in" e adicionado :COND_PAGTO2 sendo PIX
    // a troca para "in" é pra ficar mais legível em relação ao "or" com 3 condições
    QArq.Sql.Add('AND (TRANSACOES.COND_PAGTO IN (:COND_PAGTO, :COND_PAGTO1, :COND_PAGTO2, :COND_PAGTO3))');
    QArq.Sql.Add('AND (TRANSACOES.BALANCO <> :BALANCO)');
    QArq.Sql.Add('AND (TRANSACOES.DT_ENT_SAI BETWEEN :DT_INICIAL AND :DT_FINAL)');
//    QArq.Sql.Add('GROUP BY TRANSITENS.TRANSACAO_ID, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, TABELAS.COD_CONTABIL, BANCOS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
//                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('TIPO_TABELA').AsString    := '4';
    QArq.ParamByName('CONDUTA').AsString        := '01';
    QArq.ParamByName('DEPTO').AsString          := '07';
    QArq.ParamByName('MODELO').AsString         := '2D';
    QArq.ParamByName('BALANCO').AsString        := 'AGRUPADO';
    QArq.ParamByName('COND_PAGTO').AsString     := 'A VISTA';
    QArq.ParamByName('COND_PAGTO1').AsString    := 'CARTAO';
    // POISLER 03/06/2023
    QArq.ParamByName('COND_PAGTO2').AsString    := 'PIX';
    QArq.ParamByName('COND_PAGTO3').AsString    := 'CHEQUE';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



     // Remessa / Bonificação (DB Cx/Bco. - CR Cta.)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_ENT_SAI, TRANSACOES.DT_MOVIMENTO, BANCOS.COD_CONTABIL, TABELAS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR , TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    //SUM(TRANSITENS.VR_TOTAL + TRANSITENS.VALOR_ICMS_ST + TRANSITENS.VR_FRETE + TRANSITENS.VR_ACRESCIMO + TRANSITENS.VR_IPI - TRANSITENS.DESC_RODAPE)
    QArq.Sql.Add('FROM TRANSACOES');
    //QArq.Sql.Add('INNER JOIN TRANSACOES');
    //QArq.Sql.Add('ON (TRANSITENS.TRANSACAO_ID = TRANSACOES.TRANSACAO_ID)');
    QArq.Sql.Add('LEFT JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('INNER JOIN TABELAS');
    QArq.Sql.Add('ON (TRANSACOES.CONTA_ID = TABELAS.TABELA_ID AND TABELAS.TIPO_TABELA = :TIPO_TABELA)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.DEPTO = :DEPTO)');
    QArq.Sql.Add('AND (TRANSACOES.MODELO <> :MODELO)');
    QArq.Sql.Add('AND (TRANSACOES.COND_PAGTO = :COND_PAGTO)');
    QArq.Sql.Add('AND ((TRANSACOES.TIPO_VENDA = :TIPO_VENDA) OR (TRANSACOES.TIPO_VENDA = :TIPO_VENDA1))');
    QArq.Sql.Add('AND (TRANSACOES.DT_ENT_SAI BETWEEN :DT_INICIAL AND :DT_FINAL)');
//    QArq.Sql.Add('GROUP BY TRANSITENS.TRANSACAO_ID, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, TABELAS.COD_CONTABIL, BANCOS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
//                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('TIPO_TABELA').AsString    := '4';
    QArq.ParamByName('CONDUTA').AsString        := '01';
    QArq.ParamByName('DEPTO').AsString          := '07';
    QArq.ParamByName('MODELO').AsString         := '2D';
    QArq.ParamByName('COND_PAGTO').AsString     := '';
    QArq.ParamByName('TIPO_VENDA').AsString     := 'REMESSA';
    QArq.ParamByName('TIPO_VENDA1').AsString    := 'BONIFICAÇÃO';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;





    // Venda a Prazo Nfe (DB Cliente - CR Cta.)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_ENT_SAI, TRANSACOES.DT_MOVIMENTO, CLIENTES.COD_CONTABIL, TABELAS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.VALOR , TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC');
    //SUM(TRANSITENS.VR_TOTAL + TRANSITENS.VALOR_ICMS_ST + TRANSITENS.VR_FRETE + TRANSITENS.VR_ACRESCIMO + TRANSITENS.VR_IPI - TRANSITENS.DESC_RODAPE)

    QArq.Sql.Add('FROM TRANSACOES');
   // QArq.Sql.Add('INNER JOIN TRANSACOES');
   // QArq.Sql.Add('ON (TRANSITENS.TRANSACAO_ID = TRANSACOES.TRANSACAO_ID)');
    QArq.Sql.Add('INNER JOIN CLIENTES');
    QArq.Sql.Add('ON (TRANSACOES.CLIENTE_ID = CLIENTES.CLIENTE_ID)');
    QArq.Sql.Add('INNER JOIN TABELAS');
    QArq.Sql.Add('ON (TRANSACOES.CONTA_ID = TABELAS.TABELA_ID AND TABELAS.TIPO_TABELA = :TIPO_TABELA)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.DEPTO = :DEPTO)');
    QArq.Sql.Add('AND (TRANSACOES.MODELO <> :MODELO)');
    QArq.Sql.Add('AND (TRANSACOES.COND_PAGTO = :COND_PAGTO)');
    QArq.Sql.Add('AND (TRANSACOES.BALANCO <> :BALANCO)');
    QArq.Sql.Add('AND (TRANSACOES.DT_ENT_SAI BETWEEN :DT_INICIAL AND :DT_FINAL)');
 //   QArq.Sql.Add('GROUP BY TRANSITENS.TRANSACAO_ID, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, CLIENTES.COD_CONTABIL, TABELAS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
 //                'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('TIPO_TABELA').AsString    := '4';
    QArq.ParamByName('CONDUTA').AsString        := '01';
    QArq.ParamByName('DEPTO').AsString          := '07';
    QArq.ParamByName('MODELO').AsString         := '2D';
    QArq.ParamByName('COND_PAGTO').AsString     := 'A PRAZO';
    QArq.ParamByName('BALANCO').AsString        := 'AGRUPADO';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;

    // Devolução de Venda (DB Cx/Bco. - CR Cta.)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_ENT_SAI, TRANSACOES.DT_MOVIMENTO, TABELAS.COD_CONTABIL, BANCOS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO,TRANSACOES.VALOR , TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');
    //SUM(TRANSITENS.VR_TOTAL + TRANSITENS.VALOR_ICMS_ST + TRANSITENS.VR_FRETE + TRANSITENS.VR_ACRESCIMO + TRANSITENS.VR_IPI - TRANSITENS.DESC_RODAPE)
    QArq.Sql.Add('FROM TRANSACOES');
    //QArq.Sql.Add('INNER JOIN TRANSACOES');
    //QArq.Sql.Add('ON (TRANSITENS.TRANSACAO_ID = TRANSACOES.TRANSACAO_ID)');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSACOES.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('INNER JOIN TABELAS');
    QArq.Sql.Add('ON (TRANSACOES.CONTA_ID = TABELAS.TABELA_ID AND TABELAS.TIPO_TABELA = :TIPO_TABELA)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSACOES.CONDUTA = :CONDUTA)');
    QArq.Sql.Add('AND (TRANSACOES.DEPTO = :DEPTO)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');
    //QArq.Sql.Add('GROUP BY TRANSITENS.TRANSACAO_ID, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, BANCOS.COD_CONTABIL, TABELAS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
    //             'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, TRANSACOES.FLUXO_CAIXA_ID');

    QArq.ParamByName('TIPO_TRANSACAO').AsString := 'T';
    QArq.ParamByName('TIPO_TABELA').AsString    := '4';
    QArq.ParamByName('CONDUTA').AsString        := '02';
    QArq.ParamByName('DEPTO').AsString          := '10';
    QArq.ParamByName('DT_INICIAL').AsDateTime   := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime     := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Venda a Prazo c/ Entrada (DB Cx/Bco. - CR Cliente)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, BANCOS.COD_CONTABIL, CLIENTES.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSPARCELAS.VALOR, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, :FLUXO_CAIXA_ID');
    QArq.Sql.Add('FROM TRANSPARCELAS');
    QArq.Sql.Add('INNER JOIN TRANSACOES');
    QArq.Sql.Add('ON (TRANSPARCELAS.TRANSACAO_ID = TRANSACOES.TRANSACAO_ID)');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSPARCELAS.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('INNER JOIN CLIENTES');
    QArq.Sql.Add('ON (TRANSACOES.CLIENTE_ID = CLIENTES.CLIENTE_ID)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSPARCELAS.BANCO_ID > 0)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString  := 'R';
    QArq.ParamByName('FLUXO_CAIXA_ID').AsInteger := 1;
    QArq.ParamByName('DT_INICIAL').AsDateTime    := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime      := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;



    // Compra a Prazo c/ Entrada (DB Fornecedor - CR Cx/Bco.)

    QArq.Sql.Clear;
    QArq.Sql.Add('INSERT INTO RAZAO(TRANSACAO_ID, TIPO_TRANSACAO, DT_TRANS, DT_MOVIMENTO, CONTA_DB, CONTA_CR, EMPRESA_ID, C_CUSTO_ID, TPCTB, HISTORICO, VALOR, AUTORIZ_ID, NUM_DOC, FLUXO_CAIXA_ID)');
    QArq.Sql.Add('SELECT TRANSACOES.TRANSACAO_ID, :TIPO_TRANSACAO, TRANSACOES.DT_TRANS, TRANSACOES.DT_MOVIMENTO, FORNECEDORES.COD_CONTABIL, BANCOS.COD_CONTABIL, TRANSACOES.EMPRESA_ID, TRANSACOES.C_CUSTO_ID, ' +
                 'TRANSACOES.TPCTB, TRANSACOES.HISTORICO, TRANSPARCELAS.VALOR, TRANSACOES.AUTORIZ_ID, TRANSACOES.NUM_DOC, :FLUXO_CAIXA_ID');
    QArq.Sql.Add('FROM TRANSPARCELAS');
    QArq.Sql.Add('INNER JOIN TRANSACOES');
    QArq.Sql.Add('ON (TRANSPARCELAS.TRANSACAO_ID = TRANSACOES.TRANSACAO_ID)');
    QArq.Sql.Add('INNER JOIN BANCOS');
    QArq.Sql.Add('ON (TRANSPARCELAS.BANCO_ID = BANCOS.BANCO_ID)');
    QArq.Sql.Add('INNER JOIN FORNECEDORES');
    QArq.Sql.Add('ON (TRANSACOES.FORNECEDOR_ID = FORNECEDORES.FORNECEDOR_ID)');
    QArq.Sql.Add('WHERE');
    QArq.Sql.Add('(TRANSPARCELAS.BANCO_ID > 0)');
    QArq.Sql.Add('AND (TRANSACOES.DT_TRANS BETWEEN :DT_INICIAL AND :DT_FINAL)');

    QArq.ParamByName('TIPO_TRANSACAO').AsString  := 'R';
    QArq.ParamByName('FLUXO_CAIXA_ID').AsInteger := 3;
    QArq.ParamByName('DT_INICIAL').AsDateTime    := Dtmen.Date;
    QArq.ParamByName('DT_FINAL').AsDateTime      := Dtmai.Date;

    QArq.Prepare;
    QArq.ExecSql;




    Application.MessageBox('Procedimento executado com sucesso', PChar(Msg_Title), mb_IconInformation);
  finally
    btnExecuta.Enabled := True;
    btnRetorna.Enabled := True;
  end;
end;

procedure TFrmRecupera_Saldos.btnRetornaClick(Sender: TObject);
begin
  Close;
end;

procedure TFrmRecupera_Saldos.DtmenEnter(Sender: TObject);
begin
  Keybd_Event(VK_LEFT, 0, 0, 0);
end;

procedure TFrmRecupera_Saldos.DtmenKeyDown(Sender: TObject; var Key: Word;
  Shift: TShiftState);
begin
  if (Key = Vk_Return) or (Key = Vk_Down) then
    //Perform(Wm_NextDlgctl, 0, 0);

  if Key = Vk_Up then
    Perform(Wm_NextDlgctl, 1, 0);
end;

procedure TFrmRecupera_Saldos.FormClose(Sender: TObject;
  var Action: TCloseAction);
begin
  Action := caFree;
end;

procedure TFrmRecupera_Saldos.FormCreate(Sender: TObject);
begin
  Dtmen.Date := StrToDate('01/' + Copy(DateToStr(date), 4, 7));
  Dtmai.Date := Ult_Dia_Mes(date);
end;

end.
